export const INDEX_SUPPLIERS = 'INDEX_SUPPLIERS';
export const INDEX_SUPPLIERS_SUCCESS = 'INDEX_SUPPLIERS_SUCCESS';
export const INDEX_SUPPLIERS_FAIL = 'INDEX_SUPPLIERS_FAIL';

export const INDEX_CURRENCIES = 'INDEX_CURRENCIES';
export const INDEX_CURRENCIES_SUCCESS = 'INDEX_CURRENCIES_SUCCESS';
export const INDEX_CURRENCIES_FAIL = 'INDEX_CURRENCIES_FAIL';

export const DOWNLOAD_SITES = 'DOWNLOAD_SITES';
export const DOWNLOAD_SITES_SUCCESS = 'DOWNLOAD_SITES_SUCCESS';
export const DOWNLOAD_SITES_FAIL = 'DOWNLOAD_SITES_FAIL';

export const INDEX_REGIONS = 'INDEX_REGIONS';
export const INDEX_REGIONS_SUCCESS = 'INDEX_REGIONS_SUCCESS';
export const INDEX_REGIONS_FAIL = 'INDEX_REGIONS_FAIL';

export const INDEX_DISTRICTS = 'INDEX_DISTRICTS';
export const INDEX_DISTRICTS_SUCCESS = 'INDEX_DISTRICTS_SUCCESS';
export const INDEX_DISTRICTS_FAIL = 'INDEX_DISTRICTS_FAIL';

export const INDEX_COMMUNITIES = 'INDEX_COMMUNITIES';
export const INDEX_COMMUNITIES_SUCCESS = 'INDEX_COMMUNITIES_SUCCESS';
export const INDEX_COMMUNITIES_FAIL = 'INDEX_COMMUNITIES_FAIL';

export const INDEX_ORGANIZATIONS = 'INDEX_ORGANIZATIONS';
export const INDEX_ORGANIZATIONS_SUCCESS = 'INDEX_ORGANIZATIONS_SUCCESS';
export const INDEX_ORGANIZATIONS_FAIL = 'INDEX_ORGANIZATIONS_FAIL';

export const CREATE_ONE_SUPPLIER = 'CREATE_ONE_SUPPLIER';
export const CREATE_ONE_SUPPLIER_SUCCESS = 'CREATE_ONE_SUPPLIER_SUCCESS';
export const CREATE_ONE_SUPPLIER_FAIL = 'CREATE_ONE_SUPPLIER_FAIL';

export const CREATE_ONE_CURRENCY = 'CREATE_ONE_CURRENCY';
export const CREATE_ONE_CURRENCY_SUCCESS = 'CREATE_ONE_CURRENCY_SUCCESS';
export const CREATE_ONE_CURRENCY_FAIL = 'CREATE_ONE_CURRENCY_FAIL';

export const FIND_ONE_SUPPLIER = 'FIND_ONE_SUPPLIER';
export const FIND_ONE_SUPPLIER_SUCCESS = 'FIND_ONE_SUPPLIER_SUCCESS';
export const FIND_ONE_SUPPLIER_FAIL = 'FIND_ONE_SUPPLIER_FAIL';

export const DELETE_ONE_SUPPLIER = 'DELETE_ONE_SUPPLIER';
export const DELETE_ONE_SUPPLIER_SUCCESS = 'DELETE_ONE_SUPPLIER_SUCCESS';
export const DELETE_ONE_SUPPLIER_FAIL = 'DELETE_ONE_SUPPLIER_FAIL';

export const UPDATE_ONE_SUPPLIER = 'UPDATE_ONE_SUPPLIER';
export const UPDATE_ONE_SUPPLIER_SUCCESS = 'UPDATE_ONE_SUPPLIER_SUCCESS';
export const UPDATE_ONE_SUPPLIER_FAIL = 'UPDATE_ONE_SUPPLIER_FAIL';

export const INDEX_PRODUCTS = 'INDEX_PRODUCTS';
export const INDEX_PRODUCTS_SUCCESS = 'INDEX_PRODUCTS_SUCCESS';
export const INDEX_PRODUCTS_FAIL = 'INDEX_PRODUCTS_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const INDEX_USERS = 'INDEX_USERS';
export const INDEX_USERS_SUCCESS = 'INDEX_USERS_SUCCESS';
export const INDEX_USERS_FAIL = 'INDEX_USERS_FAIL';

export const CREATE_ONE_USER = 'CREATE_ONE_USER';
export const CREATE_ONE_USER_SUCCESS = 'CREATE_ONE_USER_SUCCESS';
export const CREATE_ONE_USER_FAIL = 'CREATE_ONE_USER_FAIL';

export const FIND_ONE_USER = 'FIND_ONE_USER';
export const FIND_ONE_USER_SUCCESS = 'FIND_ONE_USER_SUCCESS';
export const FIND_ONE_USER_FAIL = 'FIND_ONE_USER_FAIL';

export const DELETE_ONE_USER = 'DELETE_ONE_USER';
export const DELETE_ONE_USER_SUCCESS = 'DELETE_ONE_USER_SUCCESS';
export const DELETE_ONE_USER_FAIL = 'DELETE_ONE_USER_FAIL';

export const UPDATE_ONE_USER = 'UPDATE_ONE_USER';
export const UPDATE_ONE_USER_SUCCESS = 'UPDATE_ONE_USER_SUCCESS';
export const UPDATE_ONE_USER_FAIL = 'UPDATE_ONE_USER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const INDEX_COUNTRIES = 'INDEX_COUNTRIES';
export const INDEX_COUNTRIES_SUCCESS = 'INDEX_COUNTRIES_SUCCESS';
export const INDEX_COUNTRIES_FAIL = 'INDEX_COUNTRIES_FAIL';

export const INDEX_TRANSACTIONS = 'INDEX_TRANSACTIONS';
export const INDEX_TRANSACTIONS_SUCCESS = 'INDEX_TRANSACTIONS_SUCCESS';
export const INDEX_TRANSACTIONS_FAIL = 'INDEX_TRANSACTIONS_FAIL';

export const CREATE_ONE_TRANSACTION = 'CREATE_ONE_TRANSACTION';
export const CREATE_ONE_TRANSACTION_SUCCESS = 'CREATE_ONE_TRANSACTION_SUCCESS';
export const CREATE_ONE_TRANSACTION_FAIL = 'CREATE_ONE_TRANSACTION_FAIL';

export const UPDATE_ONE_TRANSACTION = 'CREATE_ONE_TRANSACTION';
export const UPDATE_ONE_TRANSACTION_SUCCESS = 'UPDATE_ONE_TRANSACTION_SUCCESS';
export const UPDATE_ONE_TRANSACTION_FAIL = 'UPDATE_ONE_TRANSACTION_FAIL';

export const DELETE_ONE_TRANSACTION = 'DELETE_ONE_TRANSACTION';
export const DELETE_ONE_TRANSACTION_SUCCESS = 'DELETE_ONE_TRANSACTION_SUCCESS';
export const DELETE_ONE_TRANSACTION_FAIL = 'DELETE_ONE_TRANSACTION_FAIL';


export const CREATE_ONE_STATION = 'CREATE_ONE_STATION';
export const CREATE_ONE_STATION_SUCCESS = 'CREATE_ONE_STATION_SUCCESS';
export const CREATE_ONE_STATION_FAIL = 'CREATE_ONE_STATION_FAIL';

export const FIND_ONE_STATION = 'FIND_ONE_STATION';
export const FIND_ONE_STATION_SUCCESS = 'FIND_ONE_STATION_SUCCESS';
export const FIND_ONE_STATION_FAIL = 'FIND_ONE_STATION_FAIL';

export const DELETE_ONE_STATION = 'DELETE_ONE_STATION';
export const DELETE_ONE_STATION_SUCCESS = 'DELETE_ONE_STATION_SUCCESS';
export const DELETE_ONE_STATION_FAIL = 'DELETE_ONE_STATION_FAIL';

export const UPDATE_ONE_STATION = 'UPDATE_ONE_STATION';
export const UPDATE_ONE_STATION_SUCCESS = 'UPDATE_ONE_STATION_SUCCESS';
export const UPDATE_ONE_STATION_FAIL = 'UPDATE_ONE_STATION_FAIL';

export const INDEX_COMPANIES = 'INDEX_COMPANIES';
export const INDEX_COMPANIES_SUCCESS = 'INDEX_COMPANIES_SUCCESS';
export const INDEX_COMPANIES_FAIL = 'INDEX_COMPANIES_FAIL';

export const CREATE_ONE_COMPANY = 'CREATE_ONE_COMPANY';
export const CREATE_ONE_COMPANY_SUCCESS = 'CREATE_ONE_COMPANY_SUCCESS';
export const CREATE_ONE_COMPANY_FAIL = 'CREATE_ONE_COMPANY_FAIL';

export const FIND_ONE_COMPANY = 'FIND_ONE_COMPANY';
export const FIND_ONE_COMPANY_SUCCESS = 'FIND_ONE_COMPANY_SUCCESS';
export const FIND_ONE_COMPANY_FAIL = 'FIND_ONE_COMPANY_FAIL';

export const DELETE_ONE_COMPANY = 'DELETE_ONE_COMPANY';
export const DELETE_ONE_COMPANY_SUCCESS = 'DELETE_ONE_COMPANY_SUCCESS';
export const DELETE_ONE_COMPANY_FAIL = 'DELETE_ONE_COMPANY_FAIL';

export const UPDATE_ONE_COMPANY = 'UPDATE_ONE_COMPANY';
export const UPDATE_ONE_COMPANY_SUCCESS = 'UPDATE_ONE_COMPANY_SUCCESS';
export const UPDATE_ONE_COMPANY_FAIL = 'UPDATE_ONE_COMPANY_FAIL';

export const INDEX_BUSES = 'INDEX_BUSES';
export const INDEX_BUSES_SUCCESS = 'INDEX_BUSES_SUCCESS';
export const INDEX_BUSES_FAIL = 'INDEX_BUSES_FAIL';

export const CREATE_ONE_BUS = 'CREATE_ONE_BUS';
export const CREATE_ONE_BUS_SUCCESS = 'CREATE_ONE_BUS_SUCCESS';
export const CREATE_ONE_BUS_FAIL = 'CREATE_ONE_BUS_FAIL';

export const FIND_ONE_BUS = 'FIND_ONE_BUS';
export const FIND_ONE_BUS_SUCCESS = 'FIND_ONE_BUS_SUCCESS';
export const FIND_ONE_BUS_FAIL = 'FIND_ONE_BUS_FAIL';

export const DELETE_ONE_BUS = 'DELETE_ONE_BUS';
export const DELETE_ONE_BUS_SUCCESS = 'DELETE_ONE_BUS_SUCCESS';
export const DELETE_ONE_BUS_FAIL = 'DELETE_ONE_BUS_FAIL';

export const UPDATE_ONE_BUS = 'UPDATE_ONE_BUS';
export const UPDATE_ONE_BUS_SUCCESS = 'UPDATE_ONE_BUS_SUCCESS';
export const UPDATE_ONE_BUS_FAIL = 'UPDATE_ONE_BUS_FAIL';

export const INDEX_BOOKINGS = 'INDEX_BOOKINGS';
export const INDEX_BOOKINGS_SUCCESS = 'INDEX_BOOKINGS_SUCCESS';
export const INDEX_BOOKINGS_FAIL = 'INDEX_BOOKINGS_FAIL';

export const CREATE_ONE_BOOKING = 'CREATE_ONE_BOOKING';
export const CREATE_ONE_BOOKING_SUCCESS = 'CREATE_ONE_BOOKING_SUCCESS';
export const CREATE_ONE_BOOKING_FAIL = 'CREATE_ONE_BOOKING_FAIL';

export const FIND_ONE_BOOKING = 'FIND_ONE_BOOKING';
export const FIND_ONE_BOOKING_SUCCESS = 'FIND_ONE_BOOKING_SUCCESS';
export const FIND_ONE_BOOKING_FAIL = 'FIND_ONE_BOOKING_FAIL';

export const DELETE_ONE_BOOKING = 'DELETE_ONE_BOOKING';
export const DELETE_ONE_BOOKING_SUCCESS = 'DELETE_ONE_BOOKING_SUCCESS';
export const DELETE_ONE_BOOKING_FAIL = 'DELETE_ONE_BOOKING_FAIL';

export const UPDATE_ONE_BOOKING = 'UPDATE_ONE_BOOKING';
export const UPDATE_ONE_BOOKING_SUCCESS = 'UPDATE_ONE_BOOKING_SUCCESS';
export const UPDATE_ONE_BOOKING_FAIL = 'UPDATE_ONE_BOOKING_FAIL';
